### ISSUE TITLE
Cyclic reference

### ISSUE THREAD

**Issue by doncorsean** [VoxSupplyChain/json-schema-parser#1]
Getting "found cyclic reference", I'm assuming your parser does not support cyclic references?

**Comment by tptodorov** [comment]
No, it does not. 

I am still considering how to make this possible. 
Any ideas?

**Comment by doncorsean** [comment]
I'm at the reactive summit the next day or so. Will try to take a look and come up with some ideas. Need this badly for a project I'm working on

**Comment by doncorsean** [comment]
Hello, I see in your tests where you're checking for failure with the following:
`{
 "a": {"$ref": "#/b"},
 "b": {"$ref": "#/c"},
 "c": {"$ref": "#/a"}
}`

What I'm looking for is schema generation for a type that contains a property of the same type, as follows:
`{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://my.schema.com/foo",
  "type": "object",
  "title": "foo Schema",
  "description": "Describes the payload for 'foo' entities.",
  "properties": {
    "_embedded": {
      "type": "object",
      "properties": {
        "parent": {
          "type": "array",
          "items": {
            "$ref": "http://my.schema.com/foo"
          }
        }
      }
    }
  }
}`

**Comment by blast-hardcheese** [comment]
Could we just leave the unparsed reference when we discover a cyclic reference? That way the tree isn't recursive, and `json-schema-codegen` could use that reference to look up the type it should use in that place, which should be generated from somewhere else

**Comment by tptodorov** [comment]
Yes, I agree. This is the best approach I can think of right now too. We can also leave a reference Pointer in cases where it can not be resolved. 
 Would you like to give it a try?

**Comment by blast-hardcheese** [comment]
@tptodorov: Still working on getting the Swagger spec to codegen, but at least it parses now. Running into lack of `anyOf` support now, but if I remove all the definitions that use that the codegen is almost perfect (lack of `patternProperties` support in codegen is also required, currently the generated case classes are empty)

**Comment by tptodorov** [comment]
I don't see how the cyclic $ref is represented in the returned SchemaDocument.
I think, any SchemaDocument references in a SchemaDocument should be now  Either[SchemaDocument, CyclicReference], to be able to preserve the Cyclic ref in the final object tree. Then, with that codegen can work accordingly.

**Comment by blast-hardcheese** [comment]
@tptodorov: The reason I didn't go down that route is because it would require substantial refactoring of all code around `SchemaDocument`, both in the parser and in codegen. The way the code is currently written, the `$ref -> pointer` gets parsed into an `additionalSchema`, which itself is resolved into a `SchemaDocument` which knows enough about itself to generate the right class names at codegen time

**Comment by tptodorov** [comment]
fixed in release 0.11.0
